/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    colors: {
      labelColor: '#8A8A89',
      mainTextColor: '#121417',
      detailsTextFiftyOpacityColor: '#121417', // opacity 50% for text,
      rentalConditionsColor: '#363535',
      inputColor: '#F7F7FB',
      buttonTextColor: '#FFFFFF',
      buttonMainColor: '#3470FF',
      buttonHoverColor: '#0B44CD',
    },
    fontFamily: {
      sans: [
        'Manrope',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
      ],
      serif: [
        'Manrope',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
      ],
    },
    extend: {},
  },
  plugins: [require('@headlessui/tailwindcss')({ prefix: 'ui' })],
};
