/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    colors: {
      labelColor: '#8A8A89',
      mainText: '#121417',
      detailsTextFiftyOpacity: '#121417', // opacity 50% for text,
      rentalConditions: '#363535',
      inputColor: '#F7F7FB',
      buttonText: '#FFFFFF',
      buttonMain: '#3470FF',
      buttonHover: '#0B44CD',
    },
    fontFamily: {
      sans: [
        'Manrope',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
      ],
      serif: [
        'Manrope',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
      ],
    },
    extend: {},
  },
  plugins: [],
};
